# Numpy
Numpy is general purpose array processing package. It provides high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python.

In [2]:
## Lets import numpy library first
import numpy as np

In [3]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [7]:
## Multidimensional array
my_lst1 = [1,2,3,4,5]
my_lst2 = [3,4,5,6,7]
my_lst3 = [5,6,7,8,9]
arr = np.array([my_lst1, my_lst2, my_lst3])

In [8]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [9]:
arr.shape

(3, 5)

In [13]:
arr = arr.reshape(5,3)

In [14]:
arr.shape

(5, 3)

# Indexing
Indexing is used to access the array elements

In [15]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [16]:
arr[4]

5

In [17]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [3,4,5,6,7]
my_lst3 = [5,6,7,8,9]
arr = np.array([my_lst1, my_lst2, my_lst3])

In [18]:
arr[:,:]  #Print all the elements in the array 

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [19]:
arr[1:,3:]

array([[6, 7],
       [8, 9]])

In [20]:
arr[0:2,0:2]

array([[1, 2],
       [3, 4]])

In [22]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [27]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [29]:
##Copy function and broadcasting
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[3:] = 10
arr

array([ 0,  1,  2, 10, 10, 10, 10, 10, 10, 10])

In [32]:
arr1 = arr
arr1[3:] = 50

In [35]:
print(arr1)
print(arr)        #arr1 also changes the arr because array is refernce type (they are sharing the same memory) so one changes the other will automatically changes

[ 0  1  2 50 50 50 50 50 50 50]
[ 0  1  2 50 50 50 50 50 50 50]


In [41]:
arr1 = arr.copy()       # copy function is used to prevent above problem. It creates different memory location for arr1
arr1

array([ 0,  1,  2, 50, 50, 50, 50, 50, 50, 50])

In [42]:
arr1[3:] = 500
print(arr)
print(arr1)

[ 0  1  2 50 50 50 50 50 50 50]
[  0   1   2 500 500 500 500 500 500 500]


In [45]:
## Some conditions in Exploratory Data Analysis
val = 5
print(arr<val)
print(arr+val)
print(arr*val)
print(arr/val)
print(arr%val)
arr[arr<50]

[ True  True  True False False False False False False False]
[ 5  6  7 55 55 55 55 55 55 55]
[  0   5  10 250 250 250 250 250 250 250]
[ 0.   0.2  0.4 10.  10.  10.  10.  10.  10.  10. ]
[0 1 2 0 0 0 0 0 0 0]


array([0, 1, 2])

In [48]:
## Creating and Reshaping arrays in one line
arr1 = np.arange(0,10).reshape(5,2)
arr2 = np.arange(0,10).reshape(5,2)

In [49]:
arr1*arr2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [51]:
np.ones(4)   #By default datatype is float
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [52]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [53]:
##Random Distribution
np.random.rand(2,3)

array([[0.90997275, 0.93544158, 0.14371486],
       [0.84390073, 0.44563645, 0.25897253]])

In [55]:
arr_ex = np.random.randn(4,4)
arr_ex

array([[-1.70964377e+00, -1.29618673e-01,  5.89561402e-01,
        -2.37733729e-01],
       [ 9.00155063e-01, -8.76889738e-01, -1.38872035e+00,
         1.18124501e+00],
       [-1.08169863e-03, -6.98712518e-01, -1.57199100e+00,
         3.26263566e-02],
       [-9.12275222e-01,  3.90860817e-01,  8.94015634e-01,
         1.04415076e+00]])

In [59]:
np.random.randint(0,100,8)    #Between 0 to 100 select 8 numbers randomly
np.random.randint(0,100,8).reshape(4,2)

array([[22,  0],
       [12, 58],
       [ 8, 94],
       [34, 17]])

In [61]:
np.random.random_sample((2,5))

array([[0.84823883, 0.58070959, 0.07611997, 0.88082253, 0.88858916],
       [0.20866557, 0.42481629, 0.13138708, 0.72637482, 0.94594456]])